# ESTRAZIONE DATI MATRICE PENDOLARISMO

 Importo delle librerie utili

In [8]:
import numpy as np                  #libreria numerica
import pandas as pd                 #libreria manipolazione dati

Carico la matrice del pendolarismo italiana

In [9]:
ITA=pd.read_csv('matrix_pendo2011_10112014.txt',delim_whitespace=True, 
               names=['L/S','tipo_residenza','provincia_residenza','comune_residenza','sesso',
                      'motivo','luogo','provincia_spostamento','comune_spostamento','stato estero',
                      'mezzo','orario','tempo','stima','numero'])

Estraggo la matrice del pendolarismo Fvg

In [10]:
#filtro per i viaggi tra qualsiasi regione e il Friuli

filter1 = [30,31,32,93] #udine, gorizia, trieste, pordenone

FVG_andata = ITA.query('provincia_residenza == @filter1 ')   #dal friuli a qualsiasi regione
FVG_arrivo = ITA.query('provincia_spostamento == @filter1 ') #da qualsiasi regione al friuli

# filtro da Fvg ad Fvg esclusivamente

FVG = ITA.query('provincia_residenza == @filter1 and provincia_spostamento == @filter1');
FVG

,L/S,tipo_residenza,provincia_residenza,comune_residenza,sesso,motivo,luogo,provincia_spostamento,comune_spostamento,stato estero,mezzo,orario,tempo,stima,numero
2351035,L,1,30,1,1,1,1,30,1,0,05,2,2,1,ND
2351036,L,1,30,1,1,1,1,30,1,0,06,2,1,16,ND
2351037,L,1,30,1,1,1,1,30,1,0,06,2,2,1,ND
2351038,L,1,30,1,1,1,1,30,1,0,06,3,1,1,ND
2351039,L,1,30,1,1,1,1,30,1,0,08,2,1,23,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4875913,S,2,93,38,2,2,2,93,50,0,+,+,+,ND,0000001
4875914,S,2,93,41,1,1,1,93,41,0,+,+,+,ND,0000001
4875915,S,2,93,41,2,2,1,93,41,0,+,+,+,ND,0000003
4875916,S,2,93,44,1,2,1,93,44,0,+,+,+,ND,0000001
4875917,S,2,93,51,1,2,1,93,51,0,+,+,+,ND,0000001

## Definisco la matrice Mij a partire da FVG

### Legenda delle cittÃ

**Trieste**   = 1,                 provincia 32, cittÃ  6


**Udine**     = 2,     provincia 30, cittÃ  129


**Gorizia**   = 3,     provincia 31, cittÃ  7


**Pordenone** = 4,     provincia 93, cittÃ  33

### Costruisco matrici CittÃ 1-CittÃ 2

In [11]:
A1_2 = FVG.query('provincia_residenza == 32 and comune_residenza == 6 and provincia_spostamento == 30 and comune_spostamento == 129');
A1_3 = FVG.query('provincia_residenza == 32 and comune_residenza == 6 and provincia_spostamento == 31 and comune_spostamento == 7')
A1_4 = FVG.query('provincia_residenza == 32 and comune_residenza == 6 and provincia_spostamento == 93 and comune_spostamento == 33')
A2_1 = FVG.query('provincia_residenza == 30 and comune_residenza == 129 and provincia_spostamento == 32 and comune_spostamento == 6')
A2_3 = FVG.query('provincia_residenza == 30 and comune_residenza == 129 and provincia_spostamento == 31 and comune_spostamento == 7')
A2_4 = FVG.query('provincia_residenza == 30 and comune_residenza == 129 and provincia_spostamento == 93 and comune_spostamento == 33')
A3_2 = FVG.query('provincia_residenza == 31 and comune_residenza == 7 and provincia_spostamento == 30 and comune_spostamento == 129')
A3_1 = FVG.query('provincia_residenza == 31 and comune_residenza == 7 and provincia_spostamento == 32 and comune_spostamento == 6')
A3_4 = FVG.query('provincia_residenza == 31 and comune_residenza == 7 and provincia_spostamento == 93 and comune_spostamento == 33')
A4_2 = FVG.query('provincia_residenza == 93 and comune_residenza == 33 and provincia_spostamento == 30 and comune_spostamento == 129')
A4_3 = FVG.query('provincia_residenza == 93 and comune_residenza == 33 and provincia_spostamento == 31 and comune_spostamento == 7')
A4_1 = FVG.query('provincia_residenza == 93 and comune_residenza == 33 and provincia_spostamento == 32 and comune_spostamento == 6')
A1_2

,L/S,tipo_residenza,provincia_residenza,comune_residenza,sesso,motivo,luogo,provincia_spostamento,comune_spostamento,stato estero,mezzo,orario,tempo,stima,numero
2447484,L,1,32,6,1,1,2,30,129,0,01,1,4,11.78,ND
2447485,L,1,32,6,1,1,2,30,129,0,01,2,4,3.21,ND
2447486,L,1,32,6,1,1,2,30,129,0,07,1,4,1,ND
2447487,L,1,32,6,1,1,2,30,129,0,07,2,3,1,ND
2447488,S,1,32,6,1,1,2,30,129,0,+,+,+,16.99,0000025
2447489,L,1,32,6,2,1,2,30,129,0,01,1,3,3.7,ND
2447490,L,1,32,6,2,1,2,30,129,0,01,1,4,23.6,ND
2447491,L,1,32,6,2,1,2,30,129,0,01,2,3,4.12,ND
2447492,L,1,32,6,2,1,2,30,129,0,01,2,4,4.41,ND
2447493,L,1,32,6,2,1,2,30,129,0,01,3,4,1,ND
2447494,L,1,32,6,2,1,2,30,129,0,01,4,4,6.55,ND
2447495,L,1,32,6,2,1,2,30,129,0,05,2,4,1,ND
2447496,L,1,32,6,2,1,2,30,129,0,07,2,3,3.29,ND
2447497,L,1,32,6,2,1,2,30,129,0,08,1,3,1,ND
2447498,S,1,32,6,2,1,2,30,129,0,+,+,+,48.67,0000047
2448190,L,1,32,6,1,2,2,30,129,0,01,1,4,38.99,ND
2448191,L,1,32,6,1,2,2,30,129,0,01,2,4,8.23,ND
2448192,L,1,32,6,1,2,2,30,129,0,01,3,4,4.55,ND
2448193,L,1,32,6,1,2,2,30,129,0,07,1,3,31.89,ND
2448194,L,1,32,6,1,2,2,30,129,0,07,1,4,9.66,ND
2448195,L,1,32,6,1,2,2,30,129,0,07,2,3,49.13,ND
2448196,L,1,32,6,1,2,2,30,129,0,07,2,4,11.32,ND
2448197,L,1,32,6,1,2,2,30,129,0,07,3,3,9.41,ND
2448198,L,1,32,6,1,2,2,30,129,0,07,4,3,4.43,ND
2448199,L,1,32,6,1,2,2,30,129,0,07,4,4,2.33,ND
2448200,L,1,32,6,1,2,2,30,129,0,08,1,3,5.3,ND
2448201,L,1,32,6,1,2,2,30,129,0,08,4,3,2,ND
2448202,L,1,32,6,1,2,2,30,129,0,09,3,4,1,ND
2448203,S,1,32,6,1,2,2,30,129,0,+,+,+,178.24,0000194
2448204,L,1,32,6,2,2,2,30,129,0,01,1,3,3.46,ND
2448205,L,1,32,6,2,2,2,30,129,0,01,1,4,53.73,ND
2448206,L,1,32,6,2,2,2,30,129,0,01,2,4,10.84,ND
2448207,L,1,32,6,2,2,2,30,129,0,01,3,4,3.3,ND
2448208,L,1,32,6,2,2,2,30,129,0,01,4,4,2.67,ND
2448209,L,1,32,6,2,2,2,30,129,0,04,3,2,1,ND
2448210,L,1,32,6,2,2,2,30,129,0,07,1,3,6.17,ND
2448211,L,1,32,6,2,2,2,30,129,0,07,2,3,3.15,ND
2448212,L,1,32,6,2,2,2,30,129,0,07,3,3,1,ND
2448213,L,1,32,6,2,2,2,30,129,0,07,3,4,2.77,ND
2448214,L,1,32,6,2,2,2,30,129,0,07,4,3,1,ND
2448215,S,1,32,6,2,2,2,30,129,0,+,+,+,89.09,0000085

### Costruisco Mij

In [1]:

M = np.zeros((5,5));
M[1][2]= float(sum(A1_2.agg({'stima':'sum'})))
M[1][3]= float(sum(A1_3.agg({'stima':'sum'})))
M[1][4]= float(sum(A1_4.agg({'stima':'sum'})))
M[2][1]= float(sum(A2_1.agg({'stima':'sum'})))
M[2][3]= float(sum(A2_3.agg({'stima':'sum'})))
M[2][4]= float(sum(A2_4.agg({'stima':'sum'})))
M[3][1]= float(sum(A3_1.agg({'stima':'sum'})))
M[3][2]= float(sum(A3_2.agg({'stima':'sum'})))
M[3][4]= float(sum(A3_4.agg({'stima':'sum'})))
M[4][1]= float(sum(A4_1.agg({'stima':'sum'})))
M[4][2]= float(sum(A4_2.agg({'stima':'sum'})))
M[4][3]= float(sum(A4_3.agg({'stima':'sum'})))

# salvo un file Mfvg
np.savetxt("Mfvg.txt", M, delimiter=",")
 
print(M)

NameError: name 'np' is not defined